version: "2.3"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8088:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/embyCache:/var/cache/nginx/emby
    restart: always